### ISSUE TITLE
There are differences between images and compressed images

### ISSUE THREAD

**Issue by Anivial** [dabutvin/ImgBot#140]
Hello, first thank you for this awesome bot !
I realized that there were some differences between the original image and the compressed image created by ImgBot... I haven't configure anything, so i guess that the bot used the lossless compression.

![screenshot](https://user-images.githubusercontent.com/33802820/43909073-c9851bc0-9bf9-11e8-8cef-fff379846c7a.png)

You can see in the picture that the new image is darker than the original.

Edit : or maybe it is just a preview's problem, i don't really know.

**Comment by dlemstra** [comment]
Could you add a link to the PR?

**Comment by dabutvin** [comment]
We had a similar case a while back where the image looked darker in the preview view. Turned out that the border color (red vs green) for the diff view was giving off the appearance that one was darker than the other. See https://github.com/dlemstra/Magick.NET/issues/161

@Anivial if you can't link to the PR because it's in a private project do you want to make a new, public repo with just the original image in it so we can make sure? ImgBot is for sure meant to be lossless by default.  Thanks!

**Comment by Anivial** [comment]
Yes it is a private repo.
I created another public repo with the background only : https://github.com/Anivial/ImgBot-test

**Comment by dabutvin** [comment]
Thank you @Anivial !

I can see the difference clearly

https://raw.githubusercontent.com/Anivial/ImgBot-test/master/bg.png

vs

https://raw.githubusercontent.com/Anivial/ImgBot-test/374d055b0cba270ef139ab601b5f9253bcabb3f1/bg.png

**Comment by dlemstra** [comment]
This looks like an issue with the gAMA (gamma) chunk. Will need to investigate this some more. Will get back to this topic when I have more info.

**Comment by dlemstra** [comment]
I have not had/made time to investigate this further. It looks like it was not just the gAMA chunk.
