### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JuzouSatoru2** [dabutvin/ImgBot#331]
After I installed the app I waited. After an hour I went to the website and requested a new optimization, but nothing happens. Did I do something wrong or do I have to wait longer?

**Comment by dabutvin** [comment]
Hi @JuzouSatoru2 thanks for stopping by.

It looks like you have imgbot installed into 4 projects.
3 of them we went through and there are no images to compress in any of them.
We don't really have a good way of communicating that today - you just get no PR.

The 4th one, JuzouSatoru2.github.io, is pretty big and has a lot of images in it. This wasn't picked up by the normal everyday imgbot compression function right away because of it's size, however, a function with more compute should come around soon and run through these images and we can check on the results then.

**Comment by dabutvin** [comment]
Looks like it got picked up ~30 minutes ago.
Thanks for raising a ticket here and sparking further conversations.

Definitely feel free to reach out for anything else that comes up 

👍
