### ISSUE TITLE
Master Branch 

### ISSUE THREAD

**Issue by dkarthe** [dabutvin/ImgBot#354]
Hi,
It wont optimize master branch images.. its operate seperate branch only not to master branch

**Comment by dabutvin** [comment]
Hey @dkarthe thanks for opening an issue here.

I'm not sure I totally get what the problem is you are reporting. Can you link to a specific example?

**Comment by jasikpark** [comment]
Hmmm... I came to the issues tab to talk about something similar to this.

https://github.com/jasikpark/jasik-xyz/ has only received pull requests from ImgBot for the master branch and not the blog branch (the branch that actually has media I want to compress).

I just removed ImgBot from my github account and reinstalled it with permissions for jasikpark/jasik-xyz so this might change hopefully.

**Comment by danner26** [comment]
I believe @jasikpark and possibly @dkarthe are talking about the same things, we basically want to be able to set which branch we want imagebot to optimize images from. For instance, I would like my develop branch to be the one checked rather than master which receives infrequent commits, whereas develop is often being worked on and new images are being added.

**Comment by dabutvin** [comment]
thanks @danner26 for clarifying :)

We have an open issue #155 where we had some conversations a while back - is this in line with what you were thinking? Want to chime in over there?
