### ISSUE TITLE
File paths in pull request comment

### ISSUE THREAD

**Issue by thomaspark** [dabutvin/ImgBot#59]
Hey there, ImgBot is an awesome idea and nice execution! A minor thing, but I noticed that file paths are a little off in the pull request comment.

First, it looks like it might have trouble with directories starting with underscore. In [this PR](https://github.com/thomaspark/bootswatch/pull/712), `\docs_assets\img\logo-nav.png` should be `\docs\_assets\img\logo-nav.png`.

Also wrong slashes are used.

Doesn't affect functionality of the bot at all, but thought you might find it helpful.

**Comment by dabutvin** [comment]
Thanks for filing an issue!

We can mock this up in https://github.com/dabutvin/ImgBot/blob/master/ImgBot.Test/CommitMessageTests.cs and get this fixed up for sure.

**Comment by dlemstra** [comment]
The path is not properly display because of mark down. The slash before the underscore in `\docs\_assets` will escape the underscore and make it: \docs\_assets. Using forward slashes could resolve this issue. But maybe the commit message should be inside a code block to avoid any mark down issues?

I also wonder where the message `Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.` is coming from. I could not find this in the repository.

**Comment by dabutvin** [comment]
Thanks for checking it out @dlemstra.

Looking at the commit message body it actually looks okay

![image](https://user-images.githubusercontent.com/5168796/32753215-e60590ba-c880-11e7-8c87-74756cbcc5d7.png)

That message `Hey there ...` is from me crawling GitHub trying to show people how ImgBot could help them and is not part of the service once ImgBot is installed. 
In that case you would get a message like this

![image](https://user-images.githubusercontent.com/5168796/32753327-4323bb6e-c881-11e7-8c54-ab640ab81c32.png)

I think we can leave this issue open to get the slashes going the other way
